In [3]:
!kaggle competitions download -c spaceship-titanic

from zipfile import ZipFile
import os
for i in os.listdir('C:/Users/mehmu/Desktop/Titanic'):
    if '.zip' in i:
        print(i)
        with ZipFile(i, 'r') as zipObj:
            zipObj.extractall()
        os.remove(i)

spaceship-titanic.zip: Skipping, found more recently modified local copy (use --force to force download)
spaceship-titanic.zip

In [1]:
import numpy as np
import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt
import warnings 

warnings.simplefilter('ignore')

df=pd.read_csv('train.csv')
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [2]:
df.drop(['PassengerId','Name','Cabin'],axis=1,inplace=True)

In [18]:
df.corr()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
HomePlanet,1.000000,0.066672,0.045444,0.128886,0.044727,0.192271,0.057951,0.087881,0.045490,0.036847,0.100568
CryoSleep,0.066672,1.000000,-0.086718,-0.068563,-0.027145,-0.217479,-0.182926,-0.185415,-0.176685,-0.180576,0.399631
Destination,0.045444,-0.086718,1.000000,-0.007129,-0.025442,0.043516,-0.107872,0.022511,-0.054120,-0.069216,-0.115493
Age,0.128886,-0.068563,-0.007129,1.000000,0.032546,0.067215,0.131877,0.032528,0.123957,0.103424,-0.076536
VIP,0.044727,-0.027145,-0.025442,0.032546,1.000000,0.036176,0.061093,-0.014578,0.023314,0.055701,-0.014387
RoomService,0.192271,-0.217479,0.043516,0.067215,0.036176,1.000000,-0.015659,0.054898,0.011651,-0.018870,-0.243335
FoodCourt,0.057951,-0.182926,-0.107872,0.131877,0.061093,-0.015659,1.000000,-0.013888,0.223261,0.224416,0.051097
ShoppingMall,0.087881,-0.185415,0.022511,0.032528,-0.014578,0.054898,-0.013888,1.000000,0.014442,-0.004451,0.008356
Spa,0.045490,-0.176685,-0.054120,0.123957,0.023314,0.011651,0.223261,0.014442,1.000000,0.144365,-0.221511
VRDeck,0.036847,-0.180576,-0.069216,0.103424,0.055701,-0.018870,0.224416,-0.004451,0.144365,1.000000,-0.207000
Transported,0.100568,0.399631,-0.115493,-0.076536,-0.014387,-0.243335,0.051097,0.008356,-0.221511,-0.207000,1.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   object
 1   CryoSleep     8476 non-null   object
 2   Destination   8511 non-null   object
 3   Age           8514 non-null   float64
 4   VIP           8490 non-null   object
 5   RoomService   8512 non-null   float64
 6   FoodCourt     8510 non-null   float64
 7   ShoppingMall  8485 non-null   float64
 8   Spa           8510 non-null   float64
 9   VRDeck        8505 non-null   float64
 10  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(4)
memory usage: 687.8+ KB

In [3]:
df.HomePlanet.unique()

array(['Europa', 'Earth', 'Mars', nan], dtype=object)

In [4]:
df.Destination.unique()

array(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', nan], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

for i in ['HomePlanet','CryoSleep','Destination','VIP','Transported']:
    df[i]=encoder.fit_transform(df[i])
df

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,0,2,39.0,0,0.0,0.0,0.0,0.0,0.0,0
1,0,0,2,24.0,0,109.0,9.0,25.0,549.0,44.0,1
2,1,0,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0
3,1,0,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0
4,0,0,2,16.0,0,303.0,70.0,151.0,565.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...
8688,1,0,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0
8689,0,1,1,18.0,0,0.0,0.0,0.0,0.0,0.0,0
8690,0,0,2,26.0,0,0.0,0.0,1872.0,1.0,0.0,1
8691,1,0,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0
8692,1,0,2,44.0,0,126.0,4688.0,0.0,0.0,12.0,1

In [6]:
df.dropna(inplace=True)
df

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,0,2,39.0,0,0.0,0.0,0.0,0.0,0.0,0
1,0,0,2,24.0,0,109.0,9.0,25.0,549.0,44.0,1
2,1,0,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0
3,1,0,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0
4,0,0,2,16.0,0,303.0,70.0,151.0,565.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...
8688,1,0,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0
8689,0,1,1,18.0,0,0.0,0.0,0.0,0.0,0.0,0
8690,0,0,2,26.0,0,0.0,0.0,1872.0,1.0,0.0,1
8691,1,0,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0
8692,1,0,2,44.0,0,126.0,4688.0,0.0,0.0,12.0,1

In [8]:
df.isna().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [10]:
X=df.drop('Transported',axis=1)
y=df.Transported

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_scaled = scaler.fit_transform(X)

In [11]:
X_train_scaled

array([[-0.82543673,  1.15187041,  0.58165827, ..., -0.3080733 ,
        -0.26700293, -0.27385332],
       [-0.82543673, -0.73284063,  0.58165827, ..., -0.1288415 ,
         0.08449842, -0.26155674],
       [ 1.49816653, -0.73284063, -1.78625679, ..., -0.3080733 ,
         0.52325189, -0.27385332],
       ...,
       [ 2.65996816,  1.15187041,  0.58165827, ..., -0.3080733 ,
        -0.26700293, -0.27385332],
       [-0.82543673,  1.15187041, -0.60229926, ..., -0.3080733 ,
        -0.26700293, -0.27385332],
       [ 1.49816653,  1.15187041,  0.58165827, ..., -0.3080733 ,
        -0.26700293, -0.27385332]])

In [13]:
from sklearn.model_selection import cross_validate, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

In [9]:
classifiers = {
    "NB": GaussianNB(),
    "SGD": SGDClassifier(),
    "KNN": KNeighborsClassifier(), 
    "LR": LogisticRegression(max_iter=1000), 
    "DT": DecisionTreeClassifier(),
    "RF": RandomForestClassifier(n_estimators=100, max_depth=3, random_state=2),
    "SVM": SVC(),
    "MLP": MLPClassifier(max_iter=1000),
    "XGB": XGBClassifier(),
    "LGBM": LGBMClassifier()
}

results = pd.DataFrame(columns=["Classifier", "Avg_Accuracy", "Avg_F1_Score"])
for name, clf in classifiers.items():
    model = clf
    cv_results = cross_validate(
        model, X_scaled, y, cv=10,
        scoring=(['accuracy', 'f1'])
    )

    results = results.append({
        "Classifier": name,
        "Avg_Accuracy": cv_results['test_accuracy'].mean(),
        "Avg_F1_Score": cv_results['test_f1'].mean()
    }, ignore_index=True)
    
results["Avg_Overall"] = (results["Avg_Accuracy"] + results["Avg_F1_Score"]) / 2
results = results.sort_values("Avg_Overall", ascending=False)
results

  Classifier  Avg_Accuracy  Avg_F1_Score  Avg_Overall
7        MLP      0.799213      0.805895     0.802554
9       LGBM      0.796325      0.802865     0.799595
8        XGB      0.790551      0.796183     0.793367
3         LR      0.783465      0.794796     0.789130
6        SVM      0.786877      0.789088     0.787982
1        SGD      0.778871      0.790589     0.784730
2        KNN      0.760761      0.759437     0.760099
4         DT      0.737270      0.746471     0.741871
5         RF      0.743438      0.724392     0.733915
0         NB      0.699081      0.757002     0.728042

In [11]:
clf = MLPClassifier()
params = {
    'hidden_layer_sizes': (100,120,130,140),
    'alpha':(0.0001,0.0002,0.0003),
    'max_iter':(200,300,400,500)
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

Best hyperparameter: {'alpha': 0.0002, 'hidden_layer_sizes': 130, 'max_iter': 500}

In [14]:
clf=MLPClassifier()
clf.fit(X_train_scaled,y_train)

MLPClassifier()

In [15]:
clf.predict(X_test_scaled)

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [16]:
y_pred = clf.predict(X_test_scaled)
accuracy_score(y_test,y_pred)

0.8091451292246521

In [17]:
f1_score(y_test,y_pred)

0.8183194549583648